### ISSUE TITLE
When reading, map to nested objects

### ISSUE THREAD

**Issue by janniweigelt** [mganss/ExcelMapper#119] opened 2021-04-14 10:15 UTC
If I have a class like with nested objects, how do I read values into that:
Class: Person
string Name
Address Address
string phone
Class: Address
string street
string city

Excel
Name, Street, City, Phone

**Comment by mganss** [comment] 2021-04-14 12:06
If you have control over the class definitions, you could add adapter properties to class `Person`. For example:

```c#
class Person
{
    public string Name { get; set; }
    public Address Address { get; set; } = new();

    public string Street
    {
        get => Address?.Street;
        set => Address.Street = value;
    }

    public string City
    {
        get => Address?.City;
        set => Address.City = value;
    }
}

class Address
{
    public string Street { get; set; }
    public string City { get; set; }
}
```

If you don't, you can use custom mapping:

```c#
excel.AddMapping<Person>("Street", p => p.Address)
    .SetCellUsing<Address>((c, a) => c.SetCellValue(a.Street))
    .SetPropertyUsing<Person>((p, v) =>
    {
        p.Address.Street = (string)v;
        return p.Address.Street;
    });
```

**Comment by janniweigelt** [comment] 2021-04-14 12:16
Hi

I do not have control of the classes and also because of the system I am not able to use your newest version, so I am on version 5.1.218 and that seems to not have the ways you are using SetCellUsing<address>... can I do someway similar in the version I am using?

**Comment by mganss** [comment] 2021-04-14 14:30
What is the reason why you cannot use the latest version?

Another, more tedious way is to fetch dynamic objects and then manually map to static objects:

```c#
var customers = new ExcelMapper(@"customers.xlsx")
    .Fetch()
    .Select(p => new Person
    {
        Name = p.Name,
        Address = new Address
        {
            Street = p.Street,
            City = p.City
        }
    }).ToList();
```

**Comment by janniweigelt** [comment] 2021-04-14 14:42
Im working on Sitecore which is already using Microsoft.bcl.AsyncInterfaces but in version 4.700.20.21406, so I had to use a version of yours that use that.

Ok, yes I was looking at using dynamics. We were already using another mapper, but that one could not export which is why I was looking into yours. That mapper and yours cannot coexist as dll name is same: Excelmapper.dll. So keeping the old one for import and need to find another way for export... probably just using a gridview....

**Comment by mganss** [comment] 2021-04-14 15:21
Do you think that dependency issue is one that could be resolved with a change to ExcelMapper?

Which one is that other mapper with the same assembly name?

**Comment by janniweigelt** [comment] 2021-04-16 08:26
Im not sure about what you mean about changing, because if I want to use your solution then I need to use the version I mentioned. 
I'm using https://github.com/hughbe/excel-mapper

**Comment by mganss** [comment] 2021-04-16 09:49
> Im not sure about what you mean about changing, because if I want to use your solution then I need to use the version I mentioned.

I just want to make sure the dependency issue is not caused by ExcelMapper. You mentioned Sitecore: Which one's the NuGet package where the dependency issue occurs?

**Comment by janniweigelt** [comment] 2021-04-16 10:59
So im running .net 4.8 and your latest package is using System.Text.Json (>= 5.0.2), which is using Microsoft.Bcl.AsyncInterfaces (>= 5.0.0). And I have to use Microsoft.bcl.AsyncInterfaces but in version 4.700.20.21406

**Comment by mganss** [comment] 2021-04-16 14:04
What is the package name that has a dependency on Microsoft.Bcl.AsyncInterfaces version 4.700.20.21406 (presumably a Sitecore package)?

**Comment by janniweigelt** [comment] 2021-04-19 11:57
It not a nuget package but a system so I am not able to change that version.

**Comment by mganss** [comment] 2021-04-22 14:08
The original use case should now work out of the box:

```c#
class Person
{
    public string Name { get; set; }
    public Address Address { get; set; }
    public string Phone { get; set; }
}

class Address
{
    public string Street { get; set; }
    public string City { get; set; }
}

var customers = new ExcelMapper("customers.xlsx").Fetch<Person>();
```

**Closed** 2021-04-24 11:09 UTC
