### ISSUE TITLE
Fetch throwing NullReferenceException, but only part of the time.

### ISSUE THREAD

**Issue by boney0002** [mganss/ExcelMapper#111] opened 2021-03-10 19:03 UTC
I seem to be having an issue where Fetch throws a null reference exception, but only part of the time. Processing a file will work one time, and fail the next. Unfortunately I am not able to fully reproduce the issue, as it happens at random. My excel file is attached. Any advice?
[MerchCertTemplate_2.xlsx](https://github.com/mganss/ExcelMapper/files/6118258/MerchCertTemplate_2.xlsx)

**Comment by mganss** [comment] 2021-03-11 15:58
I can't repro. Please show your class definition and the reader code. Are you calling the code from multiple threads?

**Comment by TheNillesen** [comment] 2021-03-24 09:05
I have the same issue. 
I am using a FileSystemWatcher to monitor a folder. 
When an Excel file is dropped into the folder i use this package to convert the file into a list of objects. This works first time you drop a file into the folder but after the first one, it will keep throwing NullReferenceExceptions almost every time a new file being converted. 

ExceptionSource
NPOI

this is the stacktrace: 
NPOI.Util.LocaleUtil.GetLocaleCalendar(TimeZone timeZone)
   at NPOI.Util.LocaleUtil.GetLocaleCalendar()
   at NPOI.SS.UserModel.DateUtil.GetJavaCalendar(Double date, Boolean use1904windowing, TimeZone timeZone, Boolean roundSeconds)
   at NPOI.SS.UserModel.DateUtil.GetJavaDate(Double date, Boolean use1904windowing)
   at NPOI.XSSF.UserModel.XSSFCell.get_DateCellValue()
   at NPOI.SS.UserModel.DataFormatter.GetFormattedDateString(ICell cell)
   at NPOI.SS.UserModel.DataFormatter.FormatCellValue(ICell cell, IFormulaEvaluator evaluator)
   at NPOI.SS.UserModel.DataFormatter.FormatCellValue(ICell cell)
   at Ganss.Excel.ExcelMapper.GetCellValue(ICell cell, ColumnInfo targetColumn)
   at Ganss.Excel.ExcelMapper.Fetch(ISheet sheet, Type type, Func`3 valueParser)+MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by mganss** [comment] 2021-03-24 11:19
This looks like #51. Which versions of .NET, ExcelMapper, and NPOI are you using?
Please share the class definition, reader code, and an example Excel file that triggers the issue.

**Comment by mganss** [comment] 2021-04-19 09:32
If this is indeed a duplicate of #51 it should be fixed in 5.1.294. Feel free to reopen if you still encounter this.

**Closed by mganss** 2021-04-19 09:32 UTC
