### ISSUE TITLE
Incompatibility of library versions?

### ISSUE THREAD

**Issue by fox-15** [mganss/ExcelMapper#278] opened 2023-09-13 09:05 UTC
Hello!
After the release of the ExcelMapper 5.2.542 update, an error appeared when using the ClosedXML.Report 0.2.8 library. When calling the ClosedXML.Report function
var template = new XLTemplate(file);
an error started appearing:
MissingMethodException: Method not found: 

'System.Collections.Generic.IEnumerable`1<SixLabors.Fonts.GlyphMetrics> SixLabors.Fonts.FontMetrics.GetGlyphMetrics(SixLabors.Fonts.Unicode.CodePoint, SixLabors.Fonts.ColorFontSupport)'.

But how did this become possible?
These are different libraries!

While version ExcelMapper 5.2.535 works fine!

What could be causing this error?

Sincerely, Alexander

Full error text:
MissingMethodException: Method not found: 'System.Collections.Generic.IEnumerable`1<SixLabors.Fonts.GlyphMetrics> SixLabors.Fonts.FontMetrics.GetGlyphMetrics(SixLabors.Fonts.Unicode.CodePoint, SixLabors.Fonts.ColorFontSupport)'.
ClosedXML.Graphics.DefaultGraphicEngine.CalculateMaxDigitWidth(MetricId metricId)
System.Collections.Concurrent.ConcurrentDictionary<TKey, TValue>.GetOrAdd(TKey key, Func<TKey, TValue> valueFactory)
ClosedXML.Graphics.DefaultGraphicEngine.GetMaxDigitWidth(IXLFontBase fontBase, double dpiX)
ClosedXML.Excel.XLWorkbook.CalculateColumnWidth(double charWidth, IXLFont font, XLWorkbook workbook)
ClosedXML.Excel.XLWorkbook.LoadSpreadsheetDocument(SpreadsheetDocument dSpreadsheet)
ClosedXML.Excel.XLWorkbook.LoadSheets(string fileName)
ClosedXML.Report.XLTemplate..ctor(string fileName)
Dragon.Areas.Report.Controllers.RechtController.Excel_061Async(int id, int doc, EmployeeViewModel em, ParamViewModel dm) in Recht_Excel_061.cs
+ var template = new XLTemplate(file);
Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ValueTaskAwaiter<TResult>.GetResult()
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask<IActionResult> actionResultValueTask)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

**Comment by MagicAndre1981** [comment] 2023-09-13 17:56
https://github.com/ClosedXML/ClosedXML.Report/issues/326

NPOI, the lib used by ExcelMapper, made some nuget updates. Install SixLabors.Fonts 1.0 (non beta) to your project.

**Comment by fox-15** [comment] 2023-09-13 18:58
Installed SixLabors.Fonts 1.0.0 (11.08.2023) but the result is the same, cannot execute var template = new XLTemplate(file);

Method not found: 'System.Collections.Generic.IEnumerable`1<SixLabors.Fonts.GlyphMetrics> SixLabors.Fonts.FontMetrics.GetGlyphMetrics(SixLabors.Fonts.Unicode.CodePoint, SixLabors.Fonts.ColorFontSupport)'.

**Comment by MagicAndre1981** [comment] 2023-09-13 19:11
try to add this entry to csproj:

`<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>`

**Comment by fox-15** [comment] 2023-09-14 17:52
For some reason this parameter line destroyed the entire project, but it’s okay, I’ll stay on the old version, it’s not critical. Thanks for trying to help

**Comment by MagicAndre1981** [comment] 2023-09-14 18:03
wait until the other project releases a new version which also uses te stable version of SixLabors.Fonts

**Comment by tonyqus** [comment] 2023-09-28 22:39
ExcelMapper 5.2.542 is actually using SixLabors.Fonts 1.0 (Since NPOI 2.6.2 is using SixLabors.Font 1.0). 

I confirmed that ClosedXML.Report 0.2.8 also uses SixLabors.Fonts 1.0. I think this issue is nothing to do with ExcelMapper or NPOI. Can you open a issue in ClosedXML.Report repo.

**Comment by fox-15** [comment] 2023-09-29 07:28
I went back to version 5.2.528, it works without errors

**Comment by mganss** [comment] 2023-09-29 09:30
Closing this for now. ExcelMapper just has a direct dependency on NPOI, so the issue is likely somewhere else.

**Closed by mganss** 2023-09-29 09:30 UTC
